# Generated by Django 4.0.5 on 2022-06-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=10)),
                ('num_beds', models.IntegerField()),
                ('num_baths', models.IntegerField()),
                ('square_footage', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
